# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

framework:
    http_client:
        scoped_clients:
            conferences.client:
                base_uri: 'https://www.devevents-api.fr'
                headers:
                    Accept: 'application/json'
                    apikey: '%env(CONFERENCES_API_KEY)%'
